# Generated by Django 5.0.4 on 2024-04-21 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('machine_serial_no', models.CharField(max_length=100)),
                ('time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='oee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('machine_OEE', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_log',
            fields=[
                ('cycle_no', models.IntegerField()),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('duration', models.IntegerField()),
                ('good_products', models.IntegerField()),
                ('bad_product', models.IntegerField()),
            ],
        ),
    ]
