# Generated by Django 5.0.4 on 2024-04-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OEE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_log',
            name='bad_product',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product_log',
            name='good_products',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
