# Generated by Django 5.0.4 on 2024-04-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OEE', '0002_alter_product_log_bad_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_log',
            name='bad_product',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_log',
            name='good_products',
            field=models.IntegerField(),
        ),
    ]
